package com.nndi.model.joindto.admin.member;

public class MemberTotalDTO {
	
//	ID	VARCHAR2(30 BYTE)
//	ID_QUE_NUM	NUMBER
//	PHONE1	VARCHAR2(30 BYTE)
//	PHONE2	VARCHAR2(30 BYTE)
//	PHONE3	VARCHAR2(30 BYTE)
//	EMAIL1	VARCHAR2(50 BYTE)
//	EMAIL2	VARCHAR2(50 BYTE)
//	ADDRESS1	VARCHAR2(300 BYTE)
//	ADDRESS2	VARCHAR2(300 BYTE)
//	ADDRESS3	VARCHAR2(300 BYTE)
//	PWD	VARCHAR2(100 BYTE)
//	NAME	VARCHAR2(30 BYTE)
//	BIRTH	DATE
//	ID_ANSWER	VARCHAR2(100 BYTE)
//	GENDER	VARCHAR2(3 BYTE)
//	LAST_LOGIN	DATE
//	USER_STATUS	VARCHAR2(3 BYTE)
//	OUT_DATE	DATE
//	ENROLL_DATE	DATE
	
	

}
